version: "3"
services:

  httpd:
    image: crinis/typo3-httpd:2.4-alpine
    volumes:
      - typo3:/var/www/html/
    ports:
      - 80:80
    networks:
      - php
    environment:
      PHP_FPM: 'typo3:9000'

  typo3:
    image: crinis/typo3:9.5-php7.2-fpm-alpine
    volumes:
      - typo3:/var/www/html/
    networks:
      - php
      - db
    environment:
      TYPO3_ADMIN_USERNAME: 'admin'
      TYPO3_ADMIN_PASSWORD: 'ShouldBeAStrongPassword'
      TYPO3_DB_HOST: 'mysql'
      TYPO3_DB_NAME: 'typo3'
      TYPO3_DB_USERNAME: 'typo3'
      TYPO3_DB_PASSWORD: 'ShouldBeAStrongPassword'

  mysql:
    image: mysql:5.7
    volumes:
     - mysql:/var/lib/mysql
    networks:
      - db
    environment:
      MYSQL_DATABASE: 'typo3'
      MYSQL_USER: 'typo3'
      MYSQL_PASSWORD: 'ShouldBeAStrongPassword'
      MYSQL_ROOT_PASSWORD: 'ShouldBeAStrongPassword'
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'

networks:
  php:
  db:

volumes:
  typo3:
  mysql:
